### PR TITLE
to get work with sensor r503

### PR DESCRIPTION
**Pull request by seeers**

### CODE REVIEW

**Comment by seeers** [comment]
The sensor supports the `FPM_NOFINGER (0x02)` code but if `finger.getImage()` is called after `finger.image2Tz` the function `finger.searchDatabase` does not find the finger. Result from sensor:
`EF 01 FF FF FF FF 07 00 07 09 01 EE 00 00 01 06` 

Without `finger.getImage()` after `finger.image2Tz`: 
`EF 01 FF FF FF FF 07 00 07 00 00 01 00 60 00 6F` 
 ( Found ID1 with confidence of 96 )

**Comment by brianrho** [comment]
Interesting, haven't seen this before and from the datasheet, there's no explanation for why its happening. Can you send the serial output for both cases, starting from the startup message that shows the capacity? Also turn on debug to print everything.

**Comment by seeers** [comment]
Of course, I can do it next week

**Comment by seeers** [comment]
1:N MATCH test
Found fingerprint sensor!
Capacity: 200
Packet length: 128
Send any character to search for a print...

Serial Data  Out :
`EF 01 FF FF FF FF 01 00 07 13 00 00 00 00 00 1B EF 01 FF FF FF FF 01 00 03 0F 00 13 EF 01 FF FF FF FF 01 00 03 0F 00 13`
Serial Data  In :
`EF 01 FF FF FF FF 07 00 03 00 00 0A EF 01 FF FF FF FF 07 00 13 00 00 04 00 00 00 C8 00 03 FF FF FF FF 00 02 00 06 04 ED EF 01 FF FF FF FF 07 00 13 00 00 04 00 00 00 C8 00 03 FF FF FF FF 00 02 00 06 04 ED`

After send a char and scan & release finger ->  Finger not found Out:
`EF 01 FF FF FF FF 01 00 03 01 00 05 EF 01 FF FF FF FF 01 00 03 01 00 05 EF 01 FF FF FF FF 01 00 03 01 00 05 EF 01 FF FF FF FF 01 00 03 01 00 05 EF 01 FF FF FF FF 01 00 03 01 00 05 EF 01 FF FF FF FF 01 00 04 02 01 00 08 EF 01 FF FF FF FF 01 00 03 01 00 05 EF 01 FF FF FF FF 01 00 03 01 00 05 EF 01 FF FF FF FF 01 00 08 04 01 00 00 00 C8 00 D6`

After send a char and scan & release finger -> Finger not found  In:
`EF 01 FF FF FF FF 07 00 03 02 00 0C EF 01 FF FF FF FF 07 00 03 02 00 0C EF 01 FF FF FF FF 07 00 03 02 00 0C EF 01 FF FF FF FF 07 00 03 02 00 0C EF 01 FF FF FF FF 07 00 03 00 00 0A EF 01 FF FF FF FF 07 00 03 00 00 0A EF 01 FF FF FF FF 07 00 03 00 00 0A EF 01 FF FF FF FF 07 00 03 02 00 0C EF 01 FF FF FF FF 07 00 07 09 01 E3 00 00 00 FB`


After fix and send a char / put and release finger Found ID #0-> Out:
`EF 01 FF FF FF FF 01 00 03 01 00 05 EF 01 FF FF FF FF 01 00 03 01 00 05 EF 01 FF FF FF FF 01 00 03 01 00 05 EF 01 FF FF FF FF 01 00 03 01 00 05 EF 01 FF FF FF FF 01 00 04 02 01 00 08 EF 01 FF FF FF FF 01 00 08 04 01 00 00 00 C8 00 D6`

After fix and send a char / put and release finger Found ID #0  -> In:
`EF 01 FF FF FF FF 07 00 03 02 00 0C EF 01 FF FF FF FF 07 00 03 02 00 0C EF 01 FF FF FF FF 07 00 03 02 00 0C EF 01 FF FF FF FF 07 00 03 02 00 0C EF 01 FF FF FF FF 07 00 03 00 00 0A EF 01 FF FF FF FF 07 00 03 00 00 0A EF 01 FF FF FF FF 07 00 07 00 00 00 00 B1 00 BF`

**Comment by brianrho** [comment]
Huh, I imagine its because of some difference in their firmware, it would seem the template buffers are getting wiped/overwritten after each image scan. I'll merge your changes but instead move that code block _after_ the search is complete, so the option to wait till removal is still there.

**Comment by ErikPratama** [comment]
Can you share wiring ??

**Comment by brianrho** [comment]
Just search Google images.

**Comment by ErikPratama** [comment]
No led on in r503 sir

**Pull request merged**
